import express, { NextFunction } from 'express';
import mongoose from 'mongoose';
import cookieParser from 'cookie-parser';
import bodyParser from 'body-parser';
import { errors } from 'celebrate';
import userRouter from './router/user';
import cardRouter from './router/cards';
import { createUser, login } from './controllers/users';
import { requestLogger, errorLogger } from './middlewares/logger';
import auth from './middlewares/auth';
import errorsMiddleware from './middlewares/errors';
import { createUserValidator, loginValidator } from './validation/users';
import notFoundRoute from './router/error';

const { PORT = 3000, BASE_PATH = 'none' } = process.env;
const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
mongoose.connect('mongodb://localhost:27017/mestodb');
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(requestLogger);
app.post('/signin', loginValidator, login);
app.post('/signup', createUserValidator, createUser);
app.use('/users', auth, userRouter);
app.use('/cards', auth, cardRouter);
app.use('*', notFoundRoute);
app.use(errorLogger);
app.use(errors());
app.use(errorsMiddleware);
app.listen(PORT, () => {
  console.log(`Server running on port: ${PORT}`);
  console.log(BASE_PATH);
});
